apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
   replicas: 3
   selector: 
     app: myjavaapp-pod
     version: 2.6.2
   template:
    metadata:  
      labels:
         app: myjavaapp-pod
         version: 2.6.2
    spec:
        containers:
        - name: myjavaapp-container
          image: maha4iac/myonlinebooking:1
          ports:
          - containerPort: 8080