apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
   replicas: 3
   selector: 
     app: mynginx-pod
   template:
    metadata:  
      labels:
         app: mynginx-pod
    spec:
        containers:
        - name: mynginx-container
          image: nginx
          ports:
          - containerPort: 80